[package]
name = "slim_quick"
version = "0.1.0"
authors = ["Mahdi Belcaid <b.mahdi@gmail.com>"]

[dependencies]
bio = "0.11.0"
lazy_static = "1.0"
rand = "0.3.15"
multiset = "0.0.4"
time = "0.1"
bloomfilter = "0.0.12"
ndarray = "0.11.0"

[profile.release]
debug = true